### PR TITLE
feat(ddl parser): enable cluster optimized

### PR DESCRIPTION
**Pull request by aceforeverd**

### CODE REVIEW

**Comment by vagetablechicken** [comment]
ddl parser ut needs fix?

**Review by vagetablechicken — APPROVED** [review]

**Comment by aceforeverd** [comment]
> ddl parser ut needs fix?

There is still problem exists.

**Review by dl239 — APPROVED** [review]

**Comment by aceforeverd** [comment]
breaks due to physical plan change, can't encode the ExprIdNode key 
```
I0703 06:32:07.363636 36478 ddl_parser.cc:937] ttl won't update by node:                                                                  
JOIN(OUTPUT_RIGHT_ONLY, type=LastJoin, right_sort=(t2.col3 ASC), condition=, left_keys=(#88), right_keys=(#10), index_keys=)              
  SIMPLE_PROJECT(sources=(#88 -> t1.col2))                                                                                                
    REQUEST_UNION(partition_keys=(t1.col2), orders=(t1.col3 ASC), rows=(t1.col3, 2 PRECEDING, 0 CURRENT), index_keys=)                    
      DATA_PROVIDER(request=t1)                                                                                                           
      DATA_PROVIDER(table=t1)                                                                                                             
  DATA_PROVIDER(table=t2) 
```

**Comment by aceforeverd** [comment]
closing:
- there is no difference from `Data_provider` node level, a simpler physical node looks better (simpler implementation) 
- break existing tests

**Pull request closed without merging**
