### PR TITLE
chore(release): use conventional-changelog-cli to generate changelog

### LINKED ISSUE #2332: tools or workflow to generate release note
**Describe the feature you'd like**

**Additional context**

### PR DESCRIPTION
**Pull request by aceforeverd**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

close #2332 

Use [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) to generate the new changelog (draft version). 

The workflow is for local use only (no automated CI/CD):
1. first run ? `npm install` 
2. append the new changelog: `npm run-script changelog`
3. checkout `CHANGELOG.md` and tweak manully
4. you should change other documents and version number manully
5. commit change and open the release PR

### CODE REVIEW

**Comment by lumianph** [comment]
is the package-lock.json necessary?

**Comment by aceforeverd** [comment]
> is the package-lock.json necessary?

Lock dependency and also dependency of dependency, it should be more reliable after keep the lock file.

**Review by lumianph — APPROVED** [review]

**Review by vagetablechicken — APPROVED** [review]

**Comment by vagetablechicken** [comment]
> * **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
> 
> 
> close #2332
> 
> Use [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) to generate the new changelog (draft version).
> 
> The workflow is for local use only (no automated CI/CD):
> 
>     1. first run ? `npm install`
> 
>     2. append the new changelog: `npm run-script changelog`
> 
>     3. checkout `CHANGELOG.md` and tweak manully
> 
>     4. you should change other documents and version number manully
> 
>     5. commit change and open the release PR

How about add the description to a file in docs? or another place.

**Comment by aceforeverd** [comment]
> > * **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
> > 
> > close #2332
> > Use [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) to generate the new changelog (draft version).
> > The workflow is for local use only (no automated CI/CD):
> > ```
> > 1. first run ? `npm install`
> > 
> > 2. append the new changelog: `npm run-script changelog`
> > 
> > 3. checkout `CHANGELOG.md` and tweak manully
> > 
> > 4. you should change other documents and version number manully
> > 
> > 5. commit change and open the release PR
> > ```
> 
> How about add the description to a file in docs? or another place.

Part of `Release policy` from maintenance. Will list it in #1811

**Pull request merged**
