### PR TITLE
feat: use parameter expression

### PR DESCRIPTION
**Pull request by jingchen2222**
* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
update hybridse version

* **What is the current behavior?** (You can also link to an open issue here)

https://github.com/4paradigm/HybridSE/pull/182

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by imotai** [comment]
jdbc case with parameter statement is required!

**Review by imotai — APPROVED** [review]
lgtm

**Comment by jingchen2222** [comment]
feature will be supported if #248 is merge

**Comment by jingchen2222** [comment]
Closed after merging #248

**Pull request closed without merging**
