### PR TITLE
feat: support capital letters for bool like 'FALSE'

### PR DESCRIPTION
**Pull request by zekai427**
* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by dl239** [comment]
It's better to get the real value from parser instead of `bool` @jingchen2222

**Comment by jingchen2222** [comment]
> It's better to get the real value from parser instead of `bool` @jingchen2222

@dl239 What does real value mean? 

After parsing this command, the parser will return a `SetPlanNode` with a `ConstNode` of bool type.
But we fail to convert some zetasql's literal to hybridse's ConstNode.

I think this pr can fix the well. It would be better if we can add some related unit tests. @Kanekanekane

**Comment by zekai427** [comment]
> > It's better to get the real value from parser instead of `bool` @jingchen2222
> 
> @dl239 What does real value mean?
> 
> After parsing this command, the parser will return a `SetPlanNode` with a `ConstNode` of bool type. But we fail to convert some zetasql's literal to hybridse's ConstNode.
> 
> I think this pr can fix the well. It would be better if we can add some related unit tests. @Kanekanekane

Done.

**Comment by dl239** [comment]
> > It's better to get the real value from parser instead of `bool` @jingchen2222
> 
> @dl239 What does real value mean?
> 
> After parsing this command, the parser will return a `SetPlanNode` with a `ConstNode` of bool type. But we fail to convert some zetasql's literal to hybridse's ConstNode.
> 
> I think this pr can fix the well. It would be better if we can add some related unit tests. @Kanekanekane

`set  key value` statement, parser need not concern the value is bool or not? User get string value and decide how to use

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Review by dl239 — APPROVED** [review]

**Pull request merged**
