### PR TITLE
feat: enable `TestWindowUnion` test

### LINKED ISSUE #339: Enable the unit test of TestWindowUnion
The unit test of TestWindowUnion is ignored because of https://github.com/4paradigm/OpenMLDB/issues/122 .

Once the bug has been fixed, we should enable this unit test to ensure the functionality.

It is a low-hanging fruit and we just need to uncomment the code in `TestWindowUnion.scala` to enable the unit test.

### PR DESCRIPTION
**Pull request by huqianshan**
**Enable the unit test of TestWindowUnion;**
this pr try to solve this [original issue 339](https://github.com/4paradigm/OpenMLDB/issues/339)
it also related to  [gitee awarded issue I48BZD](https://gitee.com/paradigm4/OpenMLDB/issues/I48BZD)

**this pr is just to uncomment the code in TestWindowUnion.scala to enable the unit test.**

### CODE REVIEW

**Comment by aceforeverd** [comment]
let's try enable scala test: https://github.com/4paradigm/OpenMLDB/actions/runs/1274709848/workflow#L123
rm `-Dscalatest.skip=true`

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Comment by tobegit3hub** [comment]
> let's try enable scala test: https://github.com/4paradigm/OpenMLDB/actions/runs/1274709848/workflow#L123
> rm `-Dscalatest.skip=true`

The line of skipping scalatest is for Java modules which doesn't include the openmldb-batch. The tests for openmldb-batch is in https://github.com/4paradigm/OpenMLDB/blob/543ca80c77c5619a9dd4fad130c3546d05493f59/.github/workflows/java.yml . We will make the openmldb-batch as submodule later and this unit tests will also be executed before that.

**Comment by tobegit3hub** [comment]
Resolve https://github.com/4paradigm/OpenMLDB/issues/339

**Review by dl239 — APPROVED** [review]

**Pull request merged**
