### PR TITLE
docs: new shilds

### PR DESCRIPTION
**Pull request by ashish-patwal**
* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

- #313 

* **What is the current behavior?** (You can also link to an open issue here)

- Updated but reviewer requested some changes .

* **What is the new behavior (if this is a feature change)?**

- Updated links to maven and pypi repos to display version .

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

- [x] No

* **Other information**:

### CODE REVIEW

**Review by aceforeverd — APPROVED** [review]

**Comment by aceforeverd** [comment]
Good job!

**Comment by ashish-patwal** [comment]
Happy to help !!

**Comment by vagetablechicken** [comment]
@ashish-patwal has conflicts, plz fix it

**Comment by ashish-patwal** [comment]
Done

**Review by vagetablechicken — APPROVED** [review]

**Pull request merged**
