### PR TITLE
Feature: Speed up downloads of third-party dependencies in china.

### LINKED ISSUE #601: Speed up downloads of third-party dependencies
Speed up downloads of third-party dependencies in china.
Add a Chinese source mirror。

### PR DESCRIPTION
**Pull request by shawn-happy**
Speed up downloads of third-party dependencies in china.
Fixes #601

### CODE REVIEW

**Comment by jingchen2222** [comment]
@aceforeverd
Can this solution be applied to #594 ?

**Comment by jingchen2222** [comment]
@shawn-happy Thank you. 
We are working on refactoring third-party installation as well. #594

**Comment by aceforeverd** [comment]
@jingchen2222 @shawn-happy 
nice idea but who is the owner of https://github.91chifun.workers.dev/ ? 
cloudflare worker charges for data: [收费](https://github.com/hunshcn/gh-proxy#cloudflare-workers%E8%AE%A1%E8%B4%B9)
better figure out before we/they face trouble

**Comment by aceforeverd** [comment]
> @aceforeverd Can this solution be applied to #594 ?

- don't know if the mirror is stable, or that gh-proxy is active enough
- better self host a mirror site if needed
- even cloudflare, speed is not always good in china ( in different regions)

**Comment by aceforeverd** [comment]
Thanks for the contribution @shawn-happy. The pr looks like a ad-hoc fix and I'd gona close it.
Currently, you can tweak the download script manually in order to bypass the issue.

Anyway we are refactoring third party in #594 and hope come with a better solution.

**Pull request closed without merging**
