### PR TITLE
docs: update udf doc

### PR DESCRIPTION
**Pull request by dl239**

### CODE REVIEW

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Comment by lumianph** [comment]
pls also update the index.rst file, otherwise this file cannot be displayed on the web page

**Comment by lumianph** [comment]
this file: docs/zh/developer/index.rst

**Comment by dl239** [comment]
> this file: docs/zh/developer/index.rst

done

**Review by lumianph — APPROVED** [review]

**Pull request merged**
