### PR TITLE
refactor: set the constant in `getSQLStateType`

### LINKED ISSUE #1758: set the constant in getSQLStateType
https://github.com/4paradigm/OpenMLDB/blob/9389d90c260ec395c32cbae4d98a42a001183a16/java/openmldb-jdbc/src/main/java/com/_4paradigm/openmldb/jdbc/DatabaseMetaData.java#L1014-L1016

`return 0;` is not good. Change it to `sqlStateSQL99`.

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* code update

* **What is the current behavior?** (You can also link to an open issue here)
* https://github.com/4paradigm/OpenMLDB/issues/1758
* 

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

**Review by dl239 — APPROVED** [review]

**Comment by SaumyaBhushan** [comment]
@vagetablechicken  @dl239 Is this pull request ready to get merged?

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Comment by tobegit3hub** [comment]
Thanks for your contribution @SaumyaBhushan ✨

**Comment by SaumyaBhushan** [comment]
> Thanks for your contribution @SaumyaBhushan sparkles

Happy to contribute.

**Pull request merged**
