### PR TITLE
feat: add quit in shell

### PR DESCRIPTION
**Pull request by zekai427**
* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes / features)
- Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Review by tobegit3hub — COMMENTED** [review]
LGTM

考虑参考和兼容mysql的命令，用"quit"、“quit;"、"exit"、"exit;"都可以。

**Comment by tobegit3hub** [comment]
Add the new config files for standalone and keep current config files.

**Comment by zekai427** [comment]
> LGTM
> 
> 考虑参考和兼容mysql的命令，用"quit"、“quit;"、"exit"、"exit;"都可以。

Done

**Review by dl239 — APPROVED** [review]

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Pull request merged**
