### PR TITLE
docs: update-quickstart-concepts-folder

### PR DESCRIPTION
**Pull request by TanZiYen**

### CODE REVIEW

**Review by Elliezza — CHANGES_REQUESTED** [review]
Update picture modes-flow.png,
The other image is updated in PR https://github.com/4paradigm/OpenMLDB/pull/3487

**Review by Elliezza — APPROVED** [review]

**Review by lumianph — APPROVED** [review]

**Comment by lumianph** [comment]
@Elliezza there is a conflict to resolve

**Comment by Elliezza** [comment]
> @Elliezza there is a conflict to resolve

It's an image file that requires updating, please take the new one in this PR

**Comment by Elliezza** [comment]
> > @Elliezza there is a conflict to resolve
> 
> It's an image file that requires updating, please take the new one in this PR

@TanZiYen Awaiting picture update from ZiYen

**Comment by Elliezza** [comment]
@lumianph I can't resolve this conflict within the web editor. It's an image update that needs to overwrite the original image in the repo. Can you help since you have write access?

**Pull request merged**
