### PR TITLE
feat: suppoprt `exclude current_row` in long window

### PR DESCRIPTION
**Pull request by aceforeverd**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

**Comment by lumianph** [comment]
@aceforeverd for the `exclude current row`, please also remember to revise the docs to include this new syntax

**Comment by aceforeverd** [comment]
> @aceforeverd for the `exclude current row`, please also remember to revise the docs to include this new syntax

noted

**Review by zhanghaohit — APPROVED** [review]
LGTM

**Review by vagetablechicken — APPROVED** [review]

**Comment by aceforeverd** [comment]
[exclude current row](https://trello.com/c/2KPIBLFI/105-exclude-current-row)

**Pull request merged**
