### PR TITLE
docs: translate the Chinese doc of faq.md into English (#1796)

### LINKED ISSUE #1796: docs: translate the Chinese doc of faq.md into English
1. The source of the Chinese doc is here: https://github.com/4paradigm/OpenMLDB/blob/main/docs/zh/maintain/faq.md
2. The translated English doc should be saved under the path of docs/en/maintain/faq.md
3. Add the page entry to the file docs/en/maintain/index.rst

### PR DESCRIPTION
**Pull request by jmoldyvan**
I would like to add, if the translation/file gets merges is correct/file gets merged, I can do the other files

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs: translation faq.md from Chinese to English
close #1796 

* **What is the current behavior?** (You can also link to an open issue here)
an faq docs listing some questions

* **What is the new behavior (if this is a feature change)?**
same behavior just a translation

### CODE REVIEW

**Comment by lumianph** [comment]
Hi @jmoldyvan thank you for your contribution very much! 
However, please do not revise the Chinese version directly, please do the following:
1. Save the new English version as docs/en/maintain/faq.md 
2. Add the page entry to the file docs/en/maintain/index.rst (you can just add an item `faq` after `cli`)

**Review by lumianph — CHANGES_REQUESTED** [review]
Hi @jmoldyvan thank you for your contribution very much!
However, please do not revise the Chinese version directly, please do the following:
1. Save the new English version as docs/en/maintain/faq.md
2. Add the page entry to the file docs/en/maintain/index.rst (you can just add an item `faq` after `cli`)

**Comment by jmoldyvan** [comment]
yeah no problem, i can fix that up. thanks for the reply!

**Comment by jmoldyvan** [comment]
I'll probably just make a new pr by the way

**Comment by lumianph** [comment]
> 

no problem, we really appreciate your contribution.

**Pull request closed without merging**
