### PR TITLE
ci: lower NPROC on self host runner

### PR DESCRIPTION
**Pull request by aceforeverd**
default `NPROC` may kick down self host

### CODE REVIEW

**Comment by zhanghaohit** [comment]
How about other tasks in CI? 

How about we change the default value in Makefile: `NPROC ?= $(shell (nproc))` to `NPROC ?= 4`. 

Even one task using all the cpus to compile sometimes freeze the whole system. So our local compile may also not want to use all the cpus.

**Comment by aceforeverd** [comment]
> How about other tasks in CI? 
> 
> 
> 
> How about we change the default value in Makefile: `NPROC ?= $(shell (nproc))` to `NPROC ?= 4`. 
> 
> 
> 
> Even one task using all the cpus to compile sometimes freeze the whole system. So our local compile may also not want to use all the cpus.


Github runner is fine, linux is 2 core and mac is 3 core

**Comment by zhanghaohit** [comment]
> > How about other tasks in CI?
> > How about we change the default value in Makefile: `NPROC ?= $(shell (nproc))` to `NPROC ?= 4`.
> > Even one task using all the cpus to compile sometimes freeze the whole system. So our local compile may also not want to use all the cpus.
> 
> Github runner is fine, linux is 2 core and mac is 3 core

oh. ic. only cici task is self-hosted.

**Review by zhanghaohit — APPROVED** [review]

**Comment by aceforeverd** [comment]
> How about other tasks in CI? 
> 
> 
> 
> How about we change the default value in Makefile: `NPROC ?= $(shell (nproc))` to `NPROC ?= 4`. 
> 
> 
> 
> Even one task using all the cpus to compile sometimes freeze the whole system. So our local compile may also not want to use all the cpus.

Anyway,it do exist for local compile, it totally up to user to choose a preferred nproc. And we just pickup a most reliable one

**Review by dl239 — APPROVED** [review]

**Comment by aceforeverd** [comment]
[github workflow reorganization](https://trello.com/c/upawl5mF/8-github-workflow-reorganization)

**Pull request merged**
