### PR TITLE
refactor: delete unused scripts

### LINKED ISSUE #813: Delete unused scripts
The following scripts need to delete:
* steps/fesql_auto_test_cluster.sh
* steps/fesql_auto_test_python.sh
* steps/fesql_test_python.sh
* steps/checkout_hybridse_branch.sh
* steps/read_properties.sh
* steps/ut.sh
* onebox/start_onebox_on_rambuild_cluster.sh
* onebox/start_onebox_on_rambuild.sh

### PR DESCRIPTION
**Pull request by Nicholas-SR**
Deletes the following unused scripts:
-  steps/fesql_auto_test_cluster.sh
-  steps/fesql_auto_test_python.sh
-  steps/fesql_test_python.sh
-  steps/checkout_hybridse_branch.sh
-  steps/read_properties.sh
-  steps/ut.sh
-  onebox/start_onebox_on_rambuild_cluster.sh
-  onebox/start_onebox_on_rambuild.sh

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Refactor

* **What is the current behavior?** (You can also link to an open issue here)

Resolve #813 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

### CODE REVIEW

**Comment by Nicholas-SR** [comment]
Note: I am a first time contributor, please let me know if there's anything wrong with something.

**Comment by tobegit3hub** [comment]
> Note: I am a first time contributor, please let me know if there's anything wrong with something.

You may create an feature branch to commit your changes so that the `main` branch can be synchronized with the upstream. 

BTW, thanks for your contribution.

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Review by dl239 — APPROVED** [review]

**Comment by lumianph** [comment]
[community pr/issue tracking](https://trello.com/c/S4D8P57j/17-community-pr-issue-tracking)

**Pull request merged**
