### PR TITLE
style: enforece cpp style convention in hybridse 

### PR DESCRIPTION
**Pull request by FrankSzn**
This PR try to solve the problem that some api don't follow google cpp style.

The thing  this PR has done:

- [x] Change the api of EngineOptions and JitOptions' methods to follow google cpp style name

The related issues
[gitee related issue](https://gitee.com/paradigm4/OpenMLDB/issues/I48BZZ)
[286](https://github.com/4paradigm/OpenMLDB/issues/286)

### CODE REVIEW

**Comment by jingchen2222** [comment]
@FrankSzn pls fix compile error : https://github.com/4paradigm/OpenMLDB/pull/507/checks?check_run_id=3876242790
Try config cicd.yaml with local mode:
```yaml

env:
  HYBRIDSE_SOURCE: local
```

**Comment by FrankSzn** [comment]
> @FrankSzn pls fix compile error : https://github.com/4paradigm/OpenMLDB/pull/507/checks?check_run_id=3876242790 Try config cicd.yaml with local mode:
> 
> ```yaml
> env:
>   HYBRIDSE_SOURCE: local
> ```

Does the integration-test-src.yml also need local mode for HYBRIDSE_SOURCE?

**Comment by jingchen2222** [comment]
> > @FrankSzn pls fix compile error : https://github.com/4paradigm/OpenMLDB/pull/507/checks?check_run_id=3876242790 Try config cicd.yaml with local mode:
> > ```yaml
> > env:
> >   HYBRIDSE_SOURCE: local
> > ```
> 
> Does the integration-test-src.yml also need local mode for HYBRIDSE_SOURCE?

This is a problem. Given the integration-test is based on hybridse package.
In fact, we had better split the pr into two parts. One is for `hybridse` only. The other can modify OpenMLDB and batch.
In that way, we can review and merge `hybridse` changes first and deal with OpenMLDB-batch after we have deployed hybridse-lib and hybridse-sdk.

**Comment by jingchen2222** [comment]
Please fix the pr name: https://github.com/4paradigm/OpenMLDB/pull/507/checks?check_run_id=3885447726

${type}: ${pr description context}
type := feat|fix|build|...

**Comment by jingchen2222** [comment]
> @FrankSzn pls fix compile error : https://github.com/4paradigm/OpenMLDB/pull/507/checks?check_run_id=3876242790 
> ...
> Does the integration-test-src.yml also need local mode for HYBRIDSE_SOURCE?

And java.yaml. 
https://github.com/4paradigm/OpenMLDB/runs/3885447868?check_suite_focus=true

**Comment by jingchen2222** [comment]
@FrankSzn Please resolve conflicts

**Comment by FrankSzn** [comment]
> @FrankSzn Please resolve conflicts

I'm not sure whether the conflicts resolved?@jingchen2222

**Comment by jingchen2222** [comment]
> > @FrankSzn Please resolve conflicts
> 
> I'm not sure whether the conflicts resolved?@jingchen2222

Resolved already. Thanks for your job.

**Comment by jingchen2222** [comment]
@FrankSzn there are huge changes. 
image

It's weried. Maybe something goes wrong when you try to resolve conflicts. Do you merge OpenMLDB/main.

**Comment by jingchen2222** [comment]
@FrankSzn Could you please revert to the previous commit. I will resolve conflicts for you

**Comment by FrankSzn** [comment]
> @FrankSzn Could you please revert to the previous commit. I will resolve conflicts for you

Sorry for give you some extra work! I think the timeline of my branch is polluted, it is better for me to make a new branch to give a refresh PR. This PR should abort.
The new PR is[530](https://github.com/4paradigm/OpenMLDB/pull/530)

**Comment by jingchen2222** [comment]
> > @FrankSzn Could you please revert to the previous commit. I will resolve conflicts for you
> 
> Sorry for give you some extra work! I think the timeline of my branch is polluted, it is better for me to make a new branch to give a refresh PR. This PR should abort. The new PR is[530](https://github.com/4paradigm/OpenMLDB/pull/530)

It's ok.
PR will be closed when https://github.com/4paradigm/OpenMLDB/pull/530 is merged.

**Comment by aceforeverd** [comment]
move to #544

**Pull request closed without merging**
