### PR TITLE
docs: change the names of exectuion modes

### PR DESCRIPTION
**Pull request by michelle-qinqin**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
docs

* **What is the current behavior?** (You can also link to an open issue here)
the execution mode "在线模式" and "请求模式" in [集群版使用流程及执行模式](https://openmldb.ai/docs/zh/main/tutorial/modes.html)
are confusing

* **What is the new behavior (if this is a feature change)?**
change "在线模式" to "在线预览模式"
"请求模式" to "在线请求模式"
 after discussing with doctor Lu

### CODE REVIEW

**Comment by dl239** [comment]
why add `.ppt` file

**Comment by michelle-qinqin** [comment]
> why add `.ppt` file

 sorry, I commit another two files by mistake.
I repaint the figures in sql/window_clause and add this .ppt file into the images file as I didn't find the origin, editable file. But I hadn't finish checking the docs :sql/window_clause.
I will close this PR and commit a new, right one.
thank you for reminding me!

**Comment by aceforeverd** [comment]
> > why add `.ppt` file
> 
> sorry, I commit another two files by mistake. I repaint the figures in sql/window_clause and add this .ppt file into the images file as I didn't find the origin, editable file. But I hadn't finish checking the docs :sql/window_clause. I will close this PR and commit a new, right one. thank you for reminding me!

u can push new commit deleting files in this PR, no need resubmit :)

**Comment by michelle-qinqin** [comment]
thx for adivce! I' will try this method next time!

**Pull request closed without merging**
