### PR TITLE
fix: scala coverage report

### LINKED ISSUE #1375: coverage error on scoverage: No source root found for '/_w/OpenMDLB/OpenMLDB/java/openmldb-batch/src/test/scala/com/_4paradigm/batch/TestDate.scala'
Now the CICD job may fail because of java coverage plugin. Here is the error message.

wecom-temp-bba425fa8fcff775c4c9b192aa63a08e

### PR DESCRIPTION
**Pull request by aceforeverd**
This PR fix or partial fix a few issues related with coverage task in maven, I'm trying to understand the reason and give a little refactor here, but maybe I'm still not fully correctly. So have a extra check ~

1. close #1375, can tell why we break it , so I give a little refactor on `scala-maven-plugin`, reorder the goals used in `scal-maven-plugin`, which mostly based on the example in https://davidb.github.io/scala-maven-plugin/example_java.html

2. resolve (or temporally) #989, the reason is `scoverage` has kind conflict with `maven-scalatest & jacoco` ( see https://github.com/scoverage/scoverage-maven-plugin/issues/61). The PR resolve this by removing `scoverage:report` goal in the default `prepare-package` phase, so in the maven lifecycle `scoverage` won't invoke. Instead, we have to run `mvn scoverage:report` manually in order to get Scala related coverage report.

### CODE REVIEW

**Comment by aceforeverd** [comment]
jacoco report lost due to previous clean, which need resolve

**Review by zhanghaohit — APPROVED** [review]

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Comment by aceforeverd** [comment]
[bugfix-liguo](https://trello.com/c/Ut8UamBY/37-bugfix-liguo)

**Comment by gliu-nova** [comment]
Thank you @aceforeverd 
Was wrestling with this issue for a long time and your post had the solution.

**Pull request merged**
