### PR TITLE
feat: release compile image via tag push `v*` and some updates to docs

### PR DESCRIPTION
**Pull request by aceforeverd**
- release compile image via tag `v*` push
- tweak to with clause

### CODE REVIEW

**Review by dl239 — APPROVED** [review]

**Review by vagetablechicken — CHANGES_REQUESTED** [review]
The title is right? 'tweak to compile' ?

**Comment by aceforeverd** [comment]
> The title is right? 'tweak to compile' ?

help me change the title ? It's about compile image release in ci

**Comment by vagetablechicken** [comment]
> > The title is right? 'tweak to compile' ?
> 
> help me change the title ? It's about compile image release in ci

I think `trigger docker relse via 'v*' tag and doc fix` is ok, just let us know the changes. I'm confused about what compile tweaks when I read the title.

**Comment by aceforeverd** [comment]
> > > The title is right? 'tweak to compile' ?
> > 
> > 
> > help me change the title ? It's about compile image release in ci
> 
> I think `trigger docker relse via 'v*' tag and doc fix` is ok, just let us know the changes. I'm confused about what compile tweaks when I read the title.

corrected, thx

**Review by vagetablechicken — APPROVED** [review]

**Pull request merged**
