### PR TITLE
fix: delete data from associated pre-aggr table

### LINKED ISSUE #1673: delete key in pre-aggr table when delete occur in base table
**Bug Description**
aggregator is not supported `delete` yet, base and aggregate tables should be kept consistent.

**Expected Behavior**
when delete on base table, pre-aggr table and aggregator should invalid these rows.

**Steps to Reproduce**

1. 
2. 
3. 
4.

### PR DESCRIPTION
**Pull request by zhanghaohit**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix #1673

#2307 has to be fixed before this PR work correctly.

### CODE REVIEW

**Comment by nautaa** [comment]
https://github.com/4paradigm/OpenMLDB/blob/309dc04cdc16f5529ea09122c4e0d2849d1df90a/src/storage/aggregator.cc#L359-L363

There seems to be nothing to do, you can remove the warning log.

**Comment by zhanghaohit** [comment]
> 

here if we found a `kDelete` entry, we shall do `Delete(key)` again, right? in case during the recover, we recover the key in the `aggr_buffer_map_`

**Comment by zhanghaohit** [comment]
> https://github.com/4paradigm/OpenMLDB/blob/309dc04cdc16f5529ea09122c4e0d2849d1df90a/src/storage/aggregator.cc#L359-L363
> 
> There seems to be nothing to do, you can remove the warning log.

here if we found a `kDelete` entry, we shall do `Delete(key)` again, right? in case during the recover, we recover the key in the `aggr_buffer_map_`

**Comment by nautaa** [comment]
> > https://github.com/4paradigm/OpenMLDB/blob/309dc04cdc16f5529ea09122c4e0d2849d1df90a/src/storage/aggregator.cc#L359-L363
> > 
> > There seems to be nothing to do, you can remove the warning log.
> 
> here if we found a `kDelete` entry, we shall do `Delete(key)` again, right? in case during the recover, we recover the key in the `aggr_buffer_map_`

yep, you are right. aggregator maybe update in recovery phase.

**Comment by zhanghaohit** [comment]
merged after 060 release

**Review by dl239 — APPROVED** [review]

**Review by aceforeverd — APPROVED** [review]

**Review by wuyou10206 — APPROVED** [review]
checked

**Pull request merged**
