### PR TITLE
fix: fix like match string null bug and add some unit test case 

### LINKED ISSUE #867: like udf: address boundry error when executing `select like_match(___, string(NULL))`
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

this is a known issue from #841 

## Current Behavior

`select like_match(col2, 'm_ke', string(NULL)) as col from t1`

result
```log
terminated by signal SIGSEGV (Address boundary error)
```

only happens on linux, macOS passed though

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by jingchen2222**
…df development guide

* **Please check if the PR fulfills these requirements**

- The commit message follows our guidelines
- Tests for the changes have been added (for bug fixes/features)
- Docs have been added / updated (for bug fixes / features)
bug fixes and docs

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Resolve #867 

- [x] fix `like_match` with null string
- [x] Initialize Null NativeValue with empty StringRef
- [x] add related docs docs for built-in function development guide

* **What is the current behaviour?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by jingchen2222** [comment]
[sql support for LIKE](https://trello.com/c/ZgAcOGCw/26-sql-support-for-like)

**Review by aceforeverd — APPROVED** [review]

**Review by superzhaozheng — APPROVED** [review]
LGTM

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Comment by lumianph** [comment]
[bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Pull request merged**
