### PR TITLE
docs(udf): how to generate udf documents (udfs_8h.md)

### PR DESCRIPTION
**Pull request by aceforeverd**
**Uncompleted.**

- add the document for the second task in #1707 : udf doc gen
  - there needed extra code to make steps work
- also to metion #807, which related to linked udf doc problems

### CODE REVIEW

**Comment by aceforeverd** [comment]
merge after #2382

**Comment by lumianph** [comment]
help review this pr in the pr meeting @zhanghaohit @vagetablechicken

**Comment by aceforeverd** [comment]
> 

PR has reviewed this morning. Now it is necessary to review the changes of udf documents. It added new udf functions, and fixed many syntax errors.

**Review by vagetablechicken — APPROVED** [review]

**Comment by zhanghaohit** [comment]
@aceforeverd if we have multiple `RegisterExternal`, e.g., `RegisterExternal("ilike_match")`, it seems that it only extracts the first doc and totally ignoring the later docs with same udf name?

**Comment by aceforeverd** [comment]
> @aceforeverd if we have multiple `RegisterExternal`, e.g., `RegisterExternal("ilike_match")`, it seems that it only extracts the first doc and totally ignoring the later docs with same udf name?

Mostly, yes, `.doc` string is missing for the second and later, except `Supported Types` includes all overloads. 
It should be issue to `export_udf_info` or `export_udf_doc.py`, I'll track it elsewhere.

**Review by zhanghaohit — APPROVED** [review]
LGTM

**Pull request merged**
