### PR TITLE
test: add sql_sdk_test to cicd

### LINKED ISSUE #59: add sql sdk cicd

### PR DESCRIPTION
**Pull request by dl239**
* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by vagetablechicken** [comment]
Can we merge those ut scripts together? I'd prefer a uniform script.

**Comment by vagetablechicken** [comment]
Can we merge those ut scripts together? I'd prefer a uniform script.

**Comment by imotai** [comment]
no test reports ?

**Comment by dl239** [comment]
> no test reports ?

test reports will fix in another pr

**Review by imotai — APPROVED** [review]
LGTM

**Review by vagetablechicken — APPROVED** [review]
LGTM

**Pull request merged**
