### PR TITLE
feat: support predict server update

### PR DESCRIPTION
**Pull request by vagetablechicken**

### CODE REVIEW

**Comment by aceforeverd** [comment]
help resolve pylint reports https://github.com/4paradigm/OpenMLDB/runs/6663418951?check_suite_focus=true#step:5:132 ?

**Comment by aceforeverd** [comment]
@vagetablechicken will this resolve #1797  ?

**Comment by vagetablechicken** [comment]
> @vagetablechicken will this resolve #1797 ?

Nope. It just supports update model

**Review by tobegit3hub — APPROVED** [review]
LGTM

**Comment by vagetablechicken** [comment]
> https://github.com/4paradigm/OpenMLDB/runs/6663418951?check_suite_focus=true#step:5:132

So many, maybe fix later. good-first issue 😄

**Review by aceforeverd — APPROVED** [review]

**Pull request merged**
